/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.backend.jsonc --include-runtime=false --env-interface=BackendEnv projects/backend/worker-configuration.d.ts` (hash: 94f5638cbfd9a98740286a9c45619b32)
interface __BaseEnv_BackendEnv {
	BOOKS: R2Bucket;
	DB: D1Database;
	JOBS: Queue;
	APP_MODE: "local";
	OPENAI_API_KEY: string;
	OPENAI_MODEL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_BackendEnv {}
}
interface BackendEnv extends __BaseEnv_BackendEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_MODE" | "OPENAI_API_KEY" | "OPENAI_MODEL">> {}
}
